# Generated by Django 5.2.2 on 2025-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo_app', '0002_emailtitle_remove_registeremail_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='course_list_image/')),
                ('famous_course', models.CharField(max_length=100)),
                ('famous_course_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TitleForCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TitleForReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='whycoursehighlight',
            name='highlight_description',
            field=models.TextField(),
        ),
    ]
