# Generated by Django 5.2.2 on 2025-06-14 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo_app', '0003_titlecourse_titleforcourse_titleforreview_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='CourseReview',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_image',
            field=models.ImageField(default=1, upload_to='lesson_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='progress_image',
            field=models.ImageField(default=1, upload_to='progress_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='time_image',
            field=models.ImageField(default=1, upload_to='time_image/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LessonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
